Adding Nomina Catalogs
phpcfdi/sat-catalogos pull request #11
Opened 2021-03-13 22:34 UTC by AndreyPootMay

Adding the following nomina catalogs:

| Catálogo               | Método                 |
| ---------------------- | ---------------------- |
| n_TipoNomina           | tiposNominas           |
| n_TipoJornada          | tiposJornadas          |
| n_Estados              | nEstados               |
| n_OrigenesRecursos     | nOrigenesRecursos      |
| n_Bancos               | nBancos                |
| n_PeriodicidadesPagos  | nPeriodicidadesPagos   |
| n_RiesgosPuestos       | nRiesgosPuestos        |
| n_TiposDeducciones     | nTiposDeducciones      |
| n_TiposHoras           | nTiposHoras            |
| n_TiposIncapacidades   | nTiposIncapacidades    |
| n_TiposOtrosPagos      | nTiposOtrosPagos       |
| n_TiposOtrosPagos      | nTiposOtrosPagos       |
| n_TiposOtrosPagos      | nTiposOtrosPagos       |
| n_TiposPercepciones    | nTiposPercepciones     |
| n_TiposRegimenes       | nTiposRegimenes        |

## Test cases

For now I did not create many tests, but later I will create them on this branch. For now the ones I created or modified worked fine according to phpstan:

### tests/UseCase/SatCatalogosTest.php
![image](https://user-images.githubusercontent.com/28898216/111051571-0dc99000-8422-11eb-97b7-200f658e06b2.png)

### tests/Unit/NOMINA
![image](https://user-images.githubusercontent.com/28898216/111051600-449fa600-8422-11eb-83fa-88a22c362f1a.png)

![image](https://user-images.githubusercontent.com/28898216/111051610-54b78580-8422-11eb-9974-83eea91caa9d.png)

2021-03-15 04:10 UTC, eclipxe13 commented
Creo que sería mucho mejor que los métodos de acceso se llamen `nomina<Algo>` como `nTiposHoras => nominaTiposHoras`.

2021-03-15 04:22 UTC, eclipxe13 requested changes
Creo que es importante agregar más tests, tanto que usen la base de datos de pruebas como propiamente del código agregado

2021-03-15 04:22 UTC, eclipxe13 commented on docs/Catalogos.md
> +| n_TipoNomina           | tiposNominas           |
Creo que esta debiera ser una nueva tabla

2021-03-15 04:22 UTC, eclipxe13 commented on src/SatCatalogos.php
> + * @method Cfdi\UsosCfdi                usosCFDI();
Se modificó una línea que era correcta, hay que poner el texto como estaba `CFDI\UsosCfdi`

2021-03-15 04:22 UTC, eclipxe13 commented on src/SatCatalogos.php
> + * @method Nomina\TiposNominas          tiposNominas();
No se está agregando TiposContratos

2021-03-15 04:22 UTC, eclipxe13 commented on src/Repository.php
> +        self::NOMINA_ESTADOS,
No se está agregando NOMIA_ESTADOS, creo que no se debería incluir la constante

2021-03-15 04:22 UTC, eclipxe13 commented on tests/database-seed.sql
> +INSERT INTO nomina_tipos_nominas VALUES('E', 'Nómina extraordinaria');
Agregar muestras y pruebas de todos los demás catálogos que se están agregando

2021-03-15 04:22 UTC, eclipxe13 commented on src/Nomina/TipoHora.php
> +    public function __construct(string $id, string $texto, int $vigenteDesde, int $vigenteHasta)
Definición de método innecesaria

2021-03-15 04:22 UTC, eclipxe13 commented on src/Nomina/TipoIncapacidad.php
> +    public function __construct(string $id, string $texto, int $vigenteDesde, int $vigenteHasta)
Definición de método innecesaria

2021-03-15 04:22 UTC, eclipxe13 commented on src/Nomina/TipoOtroPago.php
> +    public function __construct(string $id, string $texto, int $vigenteDesde, int $vigenteHasta)
Definición de método innecesaria

2021-03-15 04:22 UTC, eclipxe13 commented on src/Nomina/TipoPercepcion.php
> +    public function __construct(string $id, string $texto, int $vigenteDesde, int $vigenteHasta)
Definición de método innecesaria

2021-03-15 04:22 UTC, eclipxe13 commented on src/Nomina/TipoRegimen.php
> +    public function __construct(string $id, string $texto, int $vigenteDesde, int $vigenteHasta)
Definición de método innecesaria

2021-03-15 04:22 UTC, eclipxe13 commented on src/Nomina/PeriodicidadPago.php
> +    public function __construct(string $id, string $texto, int $vigenteDesde, int $vigenteHasta)
Definición de método innecesaria

2021-03-15 04:22 UTC, eclipxe13 commented on src/Nomina/RiesgoPuesto.php
> +    public function __construct(string $id, string $texto, int $vigenteDesde, int $vigenteHasta)
Definición de método innecesaria

2021-03-15 04:22 UTC, eclipxe13 commented on src/Nomina/TipoContrato.php
> +    public function __construct(string $id, string $texto, int $vigenteDesde, int $vigenteHasta)
Definición de método innecesaria

2021-03-15 04:22 UTC, eclipxe13 commented on src/Nomina/TipoDeduccion.php
> +    public function __construct(string $id, string $texto, int $vigenteDesde, int $vigenteHasta)
Definición de método innecesaria

2021-03-19 15:57 UTC, AndreyPootMay commented on docs/Catalogos.md
> +| n_TipoNomina           | tiposNominas           |
Listo en `docs/Catalogos.md` están separadas y se corrigió el subfijo de cada catálogo conforme al documento de excel que se publica por el SAT.

2021-03-20 03:13 UTC, eclipxe13 approved these changes

2021-03-20 04:56 UTC, eclipxe13 commented
Anexo el listado correcto de los catálogos que se están agregando.

Dado que los nombres pueden cambiar sin tener que renombrar las clases, propongo los siguientes antes de integrar a la rama principal.

| Catálogo               | Método                | Propuesta |
| ---------------------- | --------------------- | --------------------- |
| c_Banco                | bancos                | |
| c_Estados              | estados               | |
| c_OrigenRecurso        | origenesRecursos      | |
| c_PeriodicidadPago     | periodicidadesPagos   | |
| c_RiesgoPuesto         | riesgosPuestos        | |
| c_TipoContrato         | tiposContratos        | contratos |
| c_TipoDeduccion        | tiposDeducciones      | deducciones |
| c_TipoHoras            | tiposHoras            | horasExtras |
| c_TipoIncapacidad      | tiposIncapacidades    | incapacidades |
| c_TipoJornada          | tiposJornadas         | jornadas |
| c_TipoNomina           | tiposNominas          | nominas |
| c_TipoOtroPago         | tiposOtrosPagos       | otrosTipoPago |
| c_TipoPercepcion       | tiposPercepciones     | percepciones |
| c_TipoRegimen          | tiposRegimenes        | regimenesContratacion |

Por favor, me gustaría saber su opinión.

2021-03-23 14:49 UTC, eclipxe13 commented
Gran trabajo @AndreyPootMay !

2021-03-23 14:50 UTC, merged